### PR TITLE
fix: PREV-97 - Update RHEL provided dependencies in PKGBUILD

### PR DESCRIPTION
**Pull request by federicorispo**
# Description

Update the dependencies in PKGBUILD for the new version of Pillow

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

This checklist is used as a reminder to avoid half-baked code
- [x] The PR title follows the following structure:" type[optional scope]: PREV-XX - LONG DESCRIPTION "
- [x] I have bumped both the PKGBUILD version and controller version, and they are the same.
- [x] I have correctly installed and enabled pre-commit
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] If I have introduced new dependencies I have added them to the pre-commit unittest additional_dependencies AND to the THIRDPARTIES file

### CODE REVIEW

**Comment by M0Rf30** [comment]
From the words of Matteo and its failing installation, the issue seems to be on preview, not ce. So here you should leave requirements.txt (and the hash of their .so requirements.txt in the provides) untouched.. this will produce the same issue also here.
To be more clear, the following error:
```
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libjpeg-b1f3a3b7.so.62.3.0(LIBJPEG_6.2)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64
  - nothing provides liblzma-816f5b19.so.5.2.7(XZ_5.0)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64
  - nothing provides libpng16-a57c74e2.so.16.38.0(PNG16_0)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64

```
Is due to the fact that the not-ce use Pillow with a lower version. Using the the same 9.3.0 will put the same libjpeg-b1f3a of ce

**Comment by federicorispo** [comment]
We updated the requirements on both ce and advanced version with [this PR](https://github.com/Zextras/carbonio-preview-ce/pull/24/). We tried to install ce and advanced on RHEL and both of them are not working without the update of the provided dependencies (see error below)

carbonio-preview
```
[root@sw-r01 ~]# yum install carbonio-preview
Updating Subscription Management repositories.
Last metadata expiration check: 1:42:39 ago on lun 05 dic 2022 16:15:55 CET.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libjpeg-b1f3a3b7.so.62.3.0(LIBJPEG_6.2)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64
  - nothing provides liblzma-816f5b19.so.5.2.7(XZ_5.0)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64
  - nothing provides libpng16-a57c74e2.so.16.38.0(PNG16_0)(64bit) needed by carbonio-preview-0.0.10-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
carbonio-preview-ce
```
[root@sw-r01 ~]# yum install carbonio-preview-ce
Updating Subscription Management repositories.
Last metadata expiration check: 1:44:23 ago on lun 05 dic 2022 16:15:55 CET.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libjpeg-b1f3a3b7.so.62.3.0(LIBJPEG_6.2)(64bit) needed by carbonio-preview-ce-0.2.13-1.el8.x86_64
  - nothing provides liblzma-816f5b19.so.5.2.7(XZ_5.0)(64bit) needed by carbonio-preview-ce-0.2.13-1.el8.x86_64
  - nothing provides libpng16-a57c74e2.so.16.38.0(PNG16_0)(64bit) needed by carbonio-preview-ce-0.2.13-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by RakuJa** [comment]
> Is due to the fact that the not-ce use Pillow with a lower version. 

Both ce and advanced are using the same version! The only requirement that is different is pymemcache that is not used in the ce but it's not the root of the problem.

[Here's](https://bitbucket.org/zextras/carbonio-preview/src/46a5d5b46e0e63c9765064dee98922efcf644969/requirements.txt#lines-13) the link to the Pillow version in the advanced requirements file:

**Review by M0Rf30 — APPROVED** [review]

**Review by RakuJa — APPROVED** [review]
LGTM

**Pull request merged**
